# configs/config.yaml

model:
  window_size: 10

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 20
  validation_split: 0.2
  test_split: 0.1  # Added parameter
  early_stopping_patience: 5  # Added parameter

paths:
  data_file: 'data/synthetic_sensor_data_with_anomalies.npz'
  results_dir: 'results'
  plot_config_path: 'configs/plot_config.yaml'  # Added parameter
  reasoning_rules_path: 'src/reasoning/rules.pl'  # Added parameter

symbolic_reasoning:
  enabled: true  # Flag to enable/disable symbolic reasoning
