# configs/config.yaml

model:
  window_size: 10

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 20
  validation_split: 0.2
  test_split: 0.1
  early_stopping_patience: 5

ppo:
  enabled: true  # Flag to enable/disable PPO training
  total_timesteps: 100  # Total timesteps for PPO training
  reward_weights:
    efficiency: 1.0
    satisfaction: 1.0
    safety: 1.0

paths:
  data_file: 'data/synthetic_sensor_data_with_anomalies.npz'
  results_dir: 'results'
  plot_config_path: 'configs/plot_config.yaml'
  reasoning_rules_path: 'src/reasoning/rules.pl'

symbolic_reasoning:
  enabled: true  # Flag to enable/disable symbolic reasoning
  rules_path: 'src/reasoning/rules.pl'  # Path to Prolog rules file
