# configs/config.yaml

model:
  window_size: 10
  feature_names:
    - temperature
    - vibration
    - pressure
    - operational_hours
    - efficiency_index
    - system_state
    - performance_score
  input_shape: [ 10, 7 ]
  architecture: "cnn_lstm"  # Specifies the model type
  cnn_lstm:
    conv_filters: [64, 128]  # Number of filters for each Conv1D layer
    kernel_sizes: [3, 3]      # Kernel sizes for Conv1D layers
    pool_sizes: [2, 2]        # Pool sizes for MaxPooling1D layers
    lstm_units: [100, 50]     # Units for each LSTM layer
    dropout_rates: [0.3, 0.3, 0.3, 0.3]  # Dropout rates after Conv and LSTM layers
    dense_units: 1            # Units for Dense layer
    activation: "sigmoid"     # Activation function for output layer

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 20
  validation_split: 0.2
  test_split: 0.1
  early_stopping_patience: 5

ppo:
  enabled: true  # Flag to enable/disable PPO training
  total_timesteps: 10000  # Total timesteps for PPO training
  reward_weights:
    efficiency: 1.0
    satisfaction: 1.0
    safety: 1.0

paths:
  data_file: 'data/synthetic_sensor_data_with_anomalies.npz'
  results_dir: 'results'
  plot_config_path: 'configs/plot_config.yaml'  # Change this line
  reasoning_rules_path: 'src/reasoning/rules.pl'

symbolic_reasoning:
  enabled: true
  rules_path: 'src/reasoning/rules.pl'
